name: load_future
description: Load future with progress dialog.
version: 0.1.0
homepage: https://github.com/kodal/load_future

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
